package view;

import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import java.awt.Image;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author nicol
 */
public class ConnectionChoicePage extends javax.swing.JFrame {

    /**
     * Creates new form ConnectionChoicePage
     */
    public ConnectionChoicePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        connectionChoicePage_JPanel = new javax.swing.JPanel();
        server_JLabel = new javax.swing.JLabel();
        Socket_JButton = new javax.swing.JToggleButton();
        RMI_JButton = new javax.swing.JToggleButton();
        enter_JButton = new javax.swing.JButton();
        IP_JField = new javax.swing.JTextField();
        connection_JLabel = new javax.swing.JLabel();
        ButtonGroup buttonGroup = new ButtonGroup(); // Aggiungi il ButtonGroup

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        connectionChoicePage_JPanel.setBackground(new java.awt.Color(210, 205, 137));
        connectionChoicePage_JPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        connectionChoicePage_JPanel.setForeground(new java.awt.Color(255, 255, 255));
        connectionChoicePage_JPanel.setPreferredSize(new java.awt.Dimension(300, 345));

        server_JLabel.setBackground(new java.awt.Color(61, 35, 20));
        server_JLabel.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        server_JLabel.setText("Enter the server");

        Socket_JButton.setBackground(new java.awt.Color(195, 188, 97));
        Socket_JButton.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        Socket_JButton.setText("Socket");
        Socket_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Socket_JButtonActionPerformed(evt);
            }
        });

        RMI_JButton.setBackground(new java.awt.Color(195, 188, 97));
        RMI_JButton.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        RMI_JButton.setText("RMI");
        RMI_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RMI_JButtonActionPerformed(evt);
            }
        });

        // Aggiungi i pulsanti al ButtonGroup
        buttonGroup.add(Socket_JButton);
        buttonGroup.add(RMI_JButton);

        enter_JButton.setBackground(new java.awt.Color(173, 160, 56));
        enter_JButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        enter_JButton.setText("ENTER");
        enter_JButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        enter_JButton.setEnabled(false); // Disabilita il bottone inizialmente
        enter_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_JButtonActionPerformed(evt);
            }
        });

        IP_JField.setBackground(new java.awt.Color(195, 188, 97));
        IP_JField.setText("10.193.9.134");
        IP_JField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                validateForm();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                validateForm();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                validateForm();
            }
        });
        IP_JField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IP_JFieldActionPerformed(evt);
            }
        });

        connection_JLabel.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        connection_JLabel.setText("Choose the connection");
        connection_JLabel.setToolTipText("");

        javax.swing.GroupLayout connectionChoicePage_JPanelLayout = new javax.swing.GroupLayout(connectionChoicePage_JPanel);
        connectionChoicePage_JPanel.setLayout(connectionChoicePage_JPanelLayout);
        connectionChoicePage_JPanelLayout.setHorizontalGroup(
                connectionChoicePage_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(connectionChoicePage_JPanelLayout.createSequentialGroup()
                                .addGroup(connectionChoicePage_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(connectionChoicePage_JPanelLayout.createSequentialGroup()
                                                .addGap(197, 197, 197)
                                                .addGroup(connectionChoicePage_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(connection_JLabel)
                                                        .addComponent(IP_JField)
                                                        .addComponent(server_JLabel)))
                                        .addGroup(connectionChoicePage_JPanelLayout.createSequentialGroup()
                                                .addGap(198, 198, 198)
                                                .addComponent(RMI_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Socket_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(168, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, connectionChoicePage_JPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(enter_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(208, 208, 208))
        );
        connectionChoicePage_JPanelLayout.setVerticalGroup(
                connectionChoicePage_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(connectionChoicePage_JPanelLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(connection_JLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(connectionChoicePage_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Socket_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RMI_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(75, 75, 75)
                                .addComponent(server_JLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IP_JField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89)
                                .addComponent(enter_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(connectionChoicePage_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(connectionChoicePage_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void Socket_JButtonActionPerformed(java.awt.event.ActionEvent evt) {
        validateForm();
    }

    private void enter_JButtonActionPerformed(java.awt.event.ActionEvent evt) {
        new LoginPage().setVisible(true);
        this.dispose();
    }

    private void IP_JFieldActionPerformed(java.awt.event.ActionEvent evt) {
        validateForm();
    }

    private void RMI_JButtonActionPerformed(java.awt.event.ActionEvent evt) {
        validateForm();
    }

    private void validateForm() {
        boolean isIPFilled = !IP_JField.getText().trim().isEmpty();
        boolean isButtonSelected = Socket_JButton.isSelected() || RMI_JButton.isSelected();
        enter_JButton.setEnabled(isIPFilled && isButtonSelected);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConnectionChoicePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConnectionChoicePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConnectionChoicePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConnectionChoicePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConnectionChoicePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JTextField IP_JField;
    private javax.swing.JToggleButton RMI_JButton;
    private javax.swing.JToggleButton Socket_JButton;
    private javax.swing.JPanel connectionChoicePage_JPanel;
    private javax.swing.JLabel connection_JLabel;
    private javax.swing.JButton enter_JButton;
    private javax.swing.JLabel server_JLabel;
    // End of variables declaration
}
