/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author nicol
 */
public class Lobby extends javax.swing.JFrame {

    /**
     * Creates new form Lobby
     */
    public Lobby() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lobby_JPanel = new javax.swing.JPanel();
        lobby_JLabel = new javax.swing.JLabel();
        createNewGame_JButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        games_JList = new javax.swing.JList<>();
        refresh_JButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lobby_JPanel.setBackground(new java.awt.Color(173, 221, 220));

        lobby_JLabel.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        lobby_JLabel.setText("LOBBY");

        createNewGame_JButton.setBackground(new java.awt.Color(82, 168, 167));
        createNewGame_JButton.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        createNewGame_JButton.setText("CREATE NEW GAME");
        createNewGame_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewGame_JButtonActionPerformed(evt);
            }
        });

        games_JList.setForeground(new java.awt.Color(55, 112, 111));
        games_JList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(games_JList);

        refresh_JButton.setBackground(new java.awt.Color(82, 168, 167));
        refresh_JButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        refresh_JButton.setText("Refresh");
        refresh_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_JButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lobby_JPanelLayout = new javax.swing.GroupLayout(lobby_JPanel);
        lobby_JPanel.setLayout(lobby_JPanelLayout);
        lobby_JPanelLayout.setHorizontalGroup(
                lobby_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(lobby_JPanelLayout.createSequentialGroup()
                                .addGroup(lobby_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(lobby_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(refresh_JButton)
                                                .addGroup(lobby_JPanelLayout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(lobby_JPanelLayout.createSequentialGroup()
                                                .addGap(253, 253, 253)
                                                .addComponent(createNewGame_JButton))
                                        .addGroup(lobby_JPanelLayout.createSequentialGroup()
                                                .addGap(309, 309, 309)
                                                .addComponent(lobby_JLabel)))
                                .addContainerGap(22, Short.MAX_VALUE))
        );
        lobby_JPanelLayout.setVerticalGroup(
                lobby_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(lobby_JPanelLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(lobby_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(refresh_JButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(createNewGame_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(15, Short.MAX_VALUE)
                                .addComponent(lobby_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lobby_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void refresh_JButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void createNewGame_JButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lobby().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton createNewGame_JButton;
    private javax.swing.JList<String> games_JList;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lobby_JLabel;
    private javax.swing.JPanel lobby_JPanel;
    private javax.swing.JButton refresh_JButton;
    // End of variables declaration                   
}
