/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author nicol
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        login_JPagePanel = new javax.swing.JPanel();
        codexNaturalis_JLabel = new javax.swing.JLabel();
        login_JButton = new javax.swing.JButton();
        nickname_jTextField = new javax.swing.JTextField();
        enterNickname_JLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        login_JPagePanel.setBackground(new java.awt.Color(205, 164, 201));

        codexNaturalis_JLabel.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        codexNaturalis_JLabel.setText("Codex Naturalis");

        login_JButton.setBackground(new java.awt.Color(139, 65, 131));
        login_JButton.setFont(new java.awt.Font("Sigmar One", 0, 12)); // NOI18N
        login_JButton.setText("LOGIN");
        login_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_JButtonActionPerformed(evt);
            }
        });

        nickname_jTextField.setBackground(new java.awt.Color(235, 218, 233));
        nickname_jTextField.setFont(new java.awt.Font("Segoe Print", 0, 10)); // NOI18N
        nickname_jTextField.setText("Nickname");
        nickname_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nickname_jTextFieldActionPerformed(evt);
            }
        });

        enterNickname_JLabel.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        enterNickname_JLabel.setText("Enter your Nickname");

        javax.swing.GroupLayout login_JPagePanelLayout = new javax.swing.GroupLayout(login_JPagePanel);
        login_JPagePanel.setLayout(login_JPagePanelLayout);
        login_JPagePanelLayout.setHorizontalGroup(
                login_JPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(login_JPagePanelLayout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addGroup(login_JPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(login_JPagePanelLayout.createSequentialGroup()
                                                .addComponent(nickname_jTextField)
                                                .addGap(99, 99, 99))
                                        .addGroup(login_JPagePanelLayout.createSequentialGroup()
                                                .addComponent(enterNickname_JLabel)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_JPagePanelLayout.createSequentialGroup()
                                .addContainerGap(142, Short.MAX_VALUE)
                                .addGroup(login_JPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_JPagePanelLayout.createSequentialGroup()
                                                .addComponent(login_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(215, 215, 215))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_JPagePanelLayout.createSequentialGroup()
                                                .addComponent(codexNaturalis_JLabel)
                                                .addGap(117, 117, 117))))
        );
        login_JPagePanelLayout.setVerticalGroup(
                login_JPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(login_JPagePanelLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(codexNaturalis_JLabel)
                                .addGap(42, 42, 42)
                                .addComponent(enterNickname_JLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nickname_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                                .addComponent(login_JButton)
                                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(login_JPagePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(login_JPagePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void login_JButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void nickname_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel codexNaturalis_JLabel;
    private javax.swing.JLabel enterNickname_JLabel;
    private javax.swing.JButton login_JButton;
    private javax.swing.JPanel login_JPagePanel;
    private javax.swing.JTextField nickname_jTextField;
    // End of variables declaration
}
